name: Branch Tag Action
description: Get branch tag and set to ENV
branding:
  icon: 'git-branch'
  color: 'purple'
inputs:
  ref:
    description: 'The branch or tag ref'
    required: true
    default: ${{ github.head_ref || github.ref }}
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.ref }}
